import { body } from "express-validator";
import { buildValidationMessage } from "../../helpers/validation-messages";

export const updatePlayerValidator = [
  body("fifa_version")
    .optional()
    .notEmpty().withMessage(buildValidationMessage("fifa_version", "required"))
    .bail()
    .isString().withMessage(buildValidationMessage("fifa_version", "string"))
    .bail()
    .matches(/^\d+$/).withMessage(buildValidationMessage("fifa_version", "invalid"))
    .bail()
    .isLength({ min: 2 }).withMessage(buildValidationMessage("fifa_version", "min_length", { min: 2 }))
    .bail()
    .isLength({ max: 2 }).withMessage(buildValidationMessage("fifa_version", "max_length", { max: 2 }))
  ,
  body("fifa_update")
    .optional()
    .notEmpty().withMessage(buildValidationMessage("fifa_update", "required"))
    .bail()
    .isString().withMessage(buildValidationMessage("fifa_update", "string"))
    .bail()
    .matches(/^\d+$/).withMessage(buildValidationMessage("fifa_update", "invalid"))
    .bail()
    .isLength({ min: 1 }).withMessage(buildValidationMessage("fifa_update", "min_length", { min: 1 }))
    .bail()
    .isLength({ max: 2 }).withMessage(buildValidationMessage("fifa_update", "max_length", { max: 2 }))
  ,
  body("long_name")
    .optional()
    .notEmpty().withMessage(buildValidationMessage("long_name", "required"))
    .bail()
    .isString().withMessage(buildValidationMessage("long_name", "string"))
    .bail()
    .isLength({ min: 3 }).withMessage(buildValidationMessage("long_name", "string"))
  ,
  body("player_face_url")
    .optional()
    .notEmpty().withMessage(buildValidationMessage("player_face_url", "required"))
    .bail()
    .isURL().withMessage(buildValidationMessage("player_face_url", "url"))
  ,
  body("age")
    .optional()
    .notEmpty().withMessage(buildValidationMessage("age", "required"))
    .bail()
    .isInt().withMessage(buildValidationMessage("age", "numeric"))
    .bail()
    .isInt({ min: 1 }).withMessage(buildValidationMessage("age", "min_numeric", { min: 1 }))
    .bail()
    .isInt({ max: 60 }).withMessage(buildValidationMessage("age", "max_numeric", { max: 60 }))
    .toInt()
  ,
  body("overall")
    .optional()
    .notEmpty().withMessage(buildValidationMessage("overall", "required"))
    .bail()
    .isInt().withMessage(buildValidationMessage("overall", "numeric"))
    .bail()
    .isInt({ min: 1 }).withMessage(buildValidationMessage("overall", "min_numeric", { min: 1 }))
    .bail()
    .isInt({ max: 99 }).withMessage(buildValidationMessage("overall", "max_numeric", { max: 99 }))
    .toInt()
  ,
  body("potential")
    .optional()
    .notEmpty().withMessage(buildValidationMessage("potential", "required"))
    .bail()
    .isInt().withMessage(buildValidationMessage("potential", "numeric"))
    .bail()
    .isInt({ min: 1 }).withMessage(buildValidationMessage("potential", "min_numeric", { min: 1 }))
    .bail()
    .isInt({ max: 99 }).withMessage(buildValidationMessage("potential", "max_numeric", { max: 99 }))
  ,
  body("player_positions")
    .optional()
    .notEmpty().withMessage(buildValidationMessage("player_positions", "required"))
    .bail()
    .isString().withMessage(buildValidationMessage("player_positions", "string"))
  ,
  body("nationality_name")
    .optional({ nullable: true })
    .notEmpty().withMessage(buildValidationMessage("nationality_name", "empty"))
    .bail()
    .isString().withMessage(buildValidationMessage("nationality_name", "string"))
  ,
  body("club_name")
    .optional({ nullable: true })
    .notEmpty().withMessage(buildValidationMessage("club_name", "empty"))
    .bail()
    .isString().withMessage(buildValidationMessage("club_name", "string"))
  ,
  body("preferred_foot")
    .optional({ nullable: true })
    .notEmpty().withMessage(buildValidationMessage("preferred_foot", "empty"))
    .bail()
    .isIn(['Left', 'Right']).withMessage(buildValidationMessage("preferred_foot", "invalid"))
  ,
  body("pace")
    .optional({ nullable: true })
    .notEmpty().withMessage(buildValidationMessage("pace", "empty"))
    .bail()
    .isInt().withMessage(buildValidationMessage("pace", "numeric"))
    .bail()
    .isInt({ min: 1 }).withMessage(buildValidationMessage("pace", "min_numeric", { min: 1 }))
    .bail()
    .isInt({ max: 99 }).withMessage(buildValidationMessage("pace", "max_numeric", { max: 99 }))
  ,
  body("shooting")
    .optional({ nullable: true })
    .notEmpty().withMessage(buildValidationMessage("shooting", "empty"))
    .bail()
    .isInt().withMessage(buildValidationMessage("shooting", "numeric"))
    .bail()
    .isInt({ min: 1 }).withMessage(buildValidationMessage("shooting", "min_numeric", { min: 1 }))
    .bail()
    .isInt({ max: 99 }).withMessage(buildValidationMessage("shooting", "max_numeric", { max: 99 }))
  ,
  body("passing")
    .optional({ nullable: true })
    .notEmpty().withMessage(buildValidationMessage("passing", "empty"))
    .bail()
    .isInt().withMessage(buildValidationMessage("passing", "numeric"))
    .bail()
    .isInt({ min: 1 }).withMessage(buildValidationMessage("passing", "min_numeric", { min: 1 }))
    .bail()
    .isInt({ max: 99 }).withMessage(buildValidationMessage("passing", "max_numeric", { max: 99 }))
  ,
  body("dribbling")
    .optional({ nullable: true })
    .notEmpty().withMessage(buildValidationMessage("dribbling", "empty"))
    .bail()
    .isInt().withMessage(buildValidationMessage("dribbling", "numeric"))
    .bail()
    .isInt({ min: 1 }).withMessage(buildValidationMessage("dribbling", "min_numeric", { min: 1 }))
    .bail()
    .isInt({ max: 99 }).withMessage(buildValidationMessage("dribbling", "max_numeric", { max: 99 }))
  ,
  body("defending")
    .optional({ nullable: true })
    .notEmpty().withMessage(buildValidationMessage("defending", "empty"))
    .bail()
    .isInt().withMessage(buildValidationMessage("defending", "numeric"))
    .bail()
    .isInt({ min: 1 }).withMessage(buildValidationMessage("defending", "min_numeric", { min: 1 }))
    .bail()
    .isInt({ max: 99 }).withMessage(buildValidationMessage("defending", "max_numeric", { max: 99 }))
  ,
  body("physic")
    .optional({ nullable: true })
    .notEmpty().withMessage(buildValidationMessage("physic", "empty"))
    .bail()
    .isInt().withMessage(buildValidationMessage("physic", "numeric"))
    .bail()
    .isInt({ min: 1 }).withMessage(buildValidationMessage("physic", "min_numeric", { min: 1 }))
    .bail()
    .isInt({ max: 99 }).withMessage(buildValidationMessage("physic", "max_numeric", { max: 99 }))
  ,

];
